services:
  backend:
    build:
      context: ./Backend
    container_name: she-ield-backend
    image: backend:latest
    restart: unless-stopped
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    env_file:
      - ./Backend/.env
    environment:
      BACKEND_CONTAINER_PORT: "${BACKEND_CONTAINER_PORT}"
    depends_on:
      - postgres
      - ml-service
    
  ml-service:
    build:
      context: ./ML-Services
    container_name: sheield-ml
    image: ml-services:latest
    restart: unless-stopped

    ports:
      - "${ML_SERVICE_HOST_PORT}:${ML_SERVICE_CONTAINER_PORT}"
    environment:
      ML_SERVICE_CONTAINER_PORT: "${ML_SERVICE_CONTAINER_PORT}"
      
  postgres:
    image: postgres:17.6
    container_name: sheield-postgres
    restart: unless-stopped
    command: ["postgres", "-p", "${POSTGRES_CONTAINER_PORT}"]

    env_file:
      - .env

    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
  
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
