FROM python:3.12.8
WORKDIR /src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . . 

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port \"${BACKEND_CONTAINER_PORT:?BACKEND_CONTAINER_PORT must be set}\""]


